author: Jan Drgona
email: drgona.jan@gmail.com
description: my personal webpage

layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
   facebook: jan.drgona.3
   linkedin: drgona
  # KU Leuven: https://www.kuleuven.be/wieiswie/en/person/00107194
  # medium: your_username
  # stackoverflow: your_user_id
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
   



topics:
  - name: optimal control of energy systems
    web_url: https://www.sciencedirect.com/science/article/pii/S0306261918302903
    image_url: https://github.com/drgona/BeSim/blob/master/Data/Page/BeSim_structure2.png


