author: Jan Drgona
email: drgona.jan@gmail.com
description: my personal webpage

layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  #sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    forks: true
    projects:
      - blog-test
      - drgona.github.io
      - HH_MPC_public
    # - repo-name

social_media:
   facebook: jan.drgona.3
   linkedin: drgona
  # stackoverflow: your_user_id
   twitter: jan_drgona
   googlescholar: "https://scholar.google.com/citations?user=A-EA2KsAAAAJ&hl=en&oi=ao"
  # unsplash: your_username
  # vk: your_username

topics:
  - name: optimal control of energy systems
    web_url: https://www.sciencedirect.com/science/article/pii/S0306261918302903
